---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: django
  namespace: jst
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: admin@jscorp.uz
        name: fluxbot
      messageTemplate: kubernetes updated
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: django 
  update:
    path: ./clusters/home
