apiVersion: apps/v1
kind: Deployment
metadata:
  name: django 
  namespace: jst 
  labels:
    app: django 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django 
  template:
    metadata:
      labels:
        app: django 
    spec:
      containers:
        - name: django 
          image: jscorptech/test-nginx:1.0.4 # {"$imagepolicy": "jst:django"}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django 
  namespace: jst 
spec:
  selector:
    app: django 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
