---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: django 
  namespace: jst
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-auth
  url: https://github.com/JscorpTech/kub.git
